### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by rxt30** [Software-Engineering-DHBW/noodle_backend#22]
Implement Access-Control for the routes
- [x] Course
- [x] File
- [x] Grades
- [x] Module
- [ ] ModuleItem
- [x] TimeTable
- [x] User

**Comment by DerNoob24** [comment]
missing at removeCourse
https://github.com/Software-Engineering-DHBW/noodle_backend/blob/a3b1cd8802648b72b238b1835ef97d1027bb33dd/src/routes/index.ts#L93

**Comment by rxt30** [comment]
> missing at removeCourse
> 
> https://github.com/Software-Engineering-DHBW/noodle_backend/blob/a3b1cd8802648b72b238b1835ef97d1027bb33dd/src/routes/index.ts#L93

Fixed in bddb7586002ea35ae80f38e7453f5ae303f71442
